/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/data-gather/': RouteRecordInfo<'/data-gather/', '/data-gather', Record<never, never>, Record<never, never>>,
    '/data-gather/components/DeviceCard': RouteRecordInfo<'/data-gather/components/DeviceCard', '/data-gather/components/DeviceCard', Record<never, never>, Record<never, never>>,
    '/data-gather/components/Edit': RouteRecordInfo<'/data-gather/components/Edit', '/data-gather/components/Edit', Record<never, never>, Record<never, never>>,
    '/home/Chart': RouteRecordInfo<'/home/Chart', '/home/Chart', Record<never, never>, Record<never, never>>,
    '/home/LoginModal': RouteRecordInfo<'/home/LoginModal', '/home/LoginModal', Record<never, never>, Record<never, never>>,
    '/home/Set': RouteRecordInfo<'/home/Set', '/home/Set', Record<never, never>, Record<never, never>>,
    '/home/Warn': RouteRecordInfo<'/home/Warn', '/home/Warn', Record<never, never>, Record<never, never>>,
    '/warning-config/': RouteRecordInfo<'/warning-config/', '/warning-config', Record<never, never>, Record<never, never>>,
    '/warning-config/Set': RouteRecordInfo<'/warning-config/Set', '/warning-config/Set', Record<never, never>, Record<never, never>>,
  }
}
