/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'device-manage': RouteRecordInfo<'device-manage', '/device-manage', Record<never, never>, Record<never, never>>,
    '/device-manage/components/DeviceCard': RouteRecordInfo<'/device-manage/components/DeviceCard', '/device-manage/components/DeviceCard', Record<never, never>, Record<never, never>>,
    '/device-manage/components/Edit': RouteRecordInfo<'/device-manage/components/Edit', '/device-manage/components/Edit', Record<never, never>, Record<never, never>>,
    'device-manage-edit': RouteRecordInfo<'device-manage-edit', '/device-manage/edit', Record<never, never>, Record<never, never>>,
    '/home/Chart': RouteRecordInfo<'/home/Chart', '/home/Chart', Record<never, never>, Record<never, never>>,
    '/home/Warn': RouteRecordInfo<'/home/Warn', '/home/Warn', Record<never, never>, Record<never, never>>,
    'warning-config': RouteRecordInfo<'warning-config', '/warning-config', Record<never, never>, Record<never, never>>,
    '/warning-config/components/ConfigCard': RouteRecordInfo<'/warning-config/components/ConfigCard', '/warning-config/components/ConfigCard', Record<never, never>, Record<never, never>>,
    '/warning-config/Set': RouteRecordInfo<'/warning-config/Set', '/warning-config/Set', Record<never, never>, Record<never, never>>,
  }
}
